version: "3.9"
services:
  pgtest:
    # image: postgres:14
    build: .
    container_name: pgtest
    volumes:
      - pgdatavolume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=Teste
      - POSTGRES_PASSWORD=teste#123
      - TZ=America/SaoPaulo
    networks:
      - pgnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: admin
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER="Authorised users only!"
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    networks:
      - pgnet
    depends_on:
      - pgtest
    
networks: 
  pgnet: {}

volumes:
  pgdatavolume:
    driver: local
